- name: title
  type: Case Insensitive Text
- name: body
  type: Text
- name: thread
  type: Short Text
- name: tags
  type: Short Text
- name: flow
  type: Short Text
- name: opened
  type: Date
- name: reporter
  type: Short Text
- name: mentions
  type: Short Text
